name: CI/CD Tour-Project

on:
  push:
    branches:
      - main

jobs:
  deploy-vm:
    name: Deploy on Self-Hosted Runner
    runs-on: self-hosted   # 👈 Run inside your VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t tour-project-gitlab:latest .

      - name: Stop & remove old container if exists
        run: |
          echo "Stopping old container if exists..."
          OLD_CONTAINER=$(docker ps -q -f name=tour-project-gitlab)
          if [ -n "$OLD_CONTAINER" ]; then
              docker stop tour-project-gitlab || true
              docker rm tour-project-gitlab || true
          fi

      - name: Start new container
        run: |
          echo "Starting new container..."
          docker run -d --name tour-project-gitlab -p 8088:8088 tour-project-gitlab:latest
          echo "Waiting for container to initialize..."
          sleep 5

      - name: Prune old Docker images
        run: |
          echo "Pruning old Docker images..."
          docker images -q tour-project-gitlab | tail -n +4 | xargs -r docker rmi -f

      - name: Show logs of new container
        run: |
          echo "New container logs:"
          docker logs tour-project-gitlab --tail 20
